[package]
name = "zim2waj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
indicatif = "0.17.3"
jubako = "0.1.0"
zim-rs = { path = "../zim-rs" }
